### ISSUE TITLE
Some Definition is not import to bungieapi.generated.components.schemas.destiny.definitions.__init__.py

### ISSUE THREAD

**Issue by Tian-que** [itemmanager/bungieapi#22]
* Svarog version:
* Python version:
* Operating System:

### Description

Some Definition is not import to `bungieapi.generated.components.schemas.destiny.definitions.__init__.py`

Most of the **Mobile Manifest Entity Definition** are in it, But some are not here. Here are their actual positions.
- "DestinyMetricDefinition": "metrics.DestinyMetricDefinition",
- "DestinyPresentationNodeDefinition": "presentation.DestinyPresentationNodeDefinition",
- "DestinyRecordDefinition": "records.DestinyRecordDefinition",
- "DestinySeasonPassDefinition": "seasons.DestinySeasonPassDefinition",
- "DestinyTraitDefinition": "traits.DestinyTraitDefinition", 
- "DestinyTraitCategoryDefinition": "traits.DestinyTraitCategoryDefinition", 
- "DestinyMilestoneDefinition": "milestones.DestinyMilestoneDefinition",
- "DestinyChecklistDefinition": "checklists.DestinyChecklistDefinition",
- "DestinyEnergyTypeDefinition": "energy_types.DestinyEnergyTypeDefinition", 

I don't know if this is a generator error or OpenAPI.json, which makes it less convenient to use.

In the end, this Client is so cooooooool, it saved me a lot of things. As a beginner, I learned a lot of knowledge! 
Thank you for your open source!

**Comment by dswistowski** [comment]
Hi @Tian-que , great you like it. They are not imported by design. I'm just importing only the one referenced. But you are right - it would be super useful if there will be more flat structure and one place to import types. 
Please bear in mind, it's pre-alpha version, and it's nowhere close to production quality. You should not expect any stability for this library yet. The API might change dramatically. But do I not expect it
